#!/usr/bin/env ruby

require 'json'
require 'fileutils'

BASEPATH = File.expand_path('~/.dotfiles')
profile = File.join(BASEPATH, 'profiles', "#{ARGV[1]}.json")
f = File.open(profile, 'r')
s = IO.read f
f.close
data = JSON.parse(s)

case ARGV[0]
when 'install'
  data["symlinks"].each do |k, v|
    target = File.join(ENV['HOME'], v)
    location = File.dirname(target)
    FileUtils.mkdir_p location unless Dir.exist? location
    if File.directory?(target) && !File.symlink?(target)
      FileUtils.rm_r target
    end
    FileUtils.ln_s(File.join(BASEPATH, k), target, :force => true)
  end

when 'uninstall'
  data["symlinks"].each do |k, v|
    File.unlink(File.join(ENV['HOME'], v))
  end
end
