#!/usr/bin/env ruby

require 'json'

BASEPATH = File.expand_path('~/.dotfiles')
SRCPATH = File.join(BASEPATH, 'src')
profile = File.join(BASEPATH, 'profiles', "#{ARGV[1]}.json")
f = File.open(profile, 'r')
s = IO.read f
f.close
data = JSON.parse(s)

case ARGV[0]
when 'install'
  data["symlinks"].each do |k, v|
    File.symlink(File.join(SRCPATH, k), File.join(ENV['HOME'], v))
  end

when 'uninstall'
  data["symlinks"].each do |k, v|
    File.unlink(File.join(ENV['HOME'], v))
  end
end
